apiVersion: v1
kind: ReplicationController
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 3
  selector:
    app: guestbook
  template:
    metadata:
     labels:
       app: guestbook
    spec:
      containers:
        - name: guestbook
          image: gcr.io/google-samples/gb-frontend:v4
          ports:
            - containerPort: 80
