apiVersion: v1
kind: Pod
metadata:
  name: guestbook-app-pod
  labels:
    name: guestbookapp
    app: guestbook-app
spec:
  containers:
    - name: guest-app
      image: gcr.io/google-samples/gb-frontend:v4
      ports:
        - containerPort: 80