apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    role: master
    app: redis
spec:
  replicas: 1
  selector:
    role: master
    app: redis
  template:
    metadata:
      name: redis-pod
      labels:
        role: master
        app: redis
    spec:
      containers:
        - name: redis-master
          image: redis:2.8.23
          ports:
            - containerPort: 6379
              name: redis-server