apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    role: slave
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: redis-server
  selector:
    role: slave
    app: redis
