apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis
    app: guestbook-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis
    app: guestbook-app
