apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    role: master
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: redis-server
  selector:
    role: master
    app: redis
