apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-slave
  labels:
    role: slave
    app: redis
spec:
  replicas: 2
  selector:
    role: slave
    app: redis
  template:
    metadata:
      labels:
        role: slave
        app: redis
    spec:
      containers:
        - name: redis-slave
          image: k8s.gcr.io/redis-slave:v2
          ports:
            - containerPort: 6379
              name: redis-server